### ISSUE TITLE
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)

### ISSUE THREAD

**Issue by David-Else** [wallabyjs/jsdom-quokka-plugin#11]
Hi, I have installed the `canvas` package and still get this error:
`(node: v12.1.0, TypeScript: v3.4.5, plugins: jsdom-quokka-plugin)​​​​`
```
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package) 
    at module.exports (/home/david/.quokka/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17) 
    at HTMLCanvasElementImpl.getContext (/home/david/.quokka/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5) 
    at HTMLCanvasElement.getContext (/home/david/.quokka/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:41:47) 
    at Object.<anonymous> (/home/david/sites/typescript-is-fun-take-3/src/app.js:17:31) 
    at Module._compile (internal/modules/cjs/loader.js:759:30) 
    at Object.quokkaStackTraceMarker (/home/david/.vscode/extensions/wallabyjs.quokka-vscode-1.0.213/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:5588) 
    at a.quokkaStackTraceMarker [as _onStart] (/home/david/.vscode/extensions/wallabyjs.quokka-vscode-1.0.213/dist/wallaby/runners/node/quokka@1.0.0/initializer.js:14:5629) 
    at a.start (/home/david/.vscode/extensions/wallabyjs.quokka-vscode-1.0.213/dist/wallaby/server.js:20:5054) 
    at D.in:run (/home/david/.vscode/extensions/wallabyjs.quokka-vscode-1.0.213/dist/wallaby/server.js:16:29962) 
    at WebSocket.<anonymous> (/home/david/.vscode/extensions/wallabyjs.quokka-vscode-1.0.213/dist/wallaby/server.js:16:28717) 
    at WebSocket.emit (events.js:196:13) 
    at Receiver.ontext (/home/david/.vscode/extensions/wallabyjs.quokka-vscode-1.0.213/dist/wallaby/node_modules/ws/lib/WebSocket.js:841:10) 
    at /home/david/.vscode/extensions/wallabyjs.quokka-vscode-1.0.213/dist/wallaby/node_modules/ws/lib/Receiver.js:536:18 
    at /home/david/.vscode/extensions/wallabyjs.quokka-vscode-1.0.213/dist/wallaby/node_modules/ws/lib/Receiver.js:368:7 
    at /home/david/.vscode/extensions/wallabyjs.quokka-vscode-1.0.213/dist/wallaby/node_modules/ws/lib/PerMessageDeflate.js:249:5 
    at afterWrite (_stream_writable.js:483:3) 
    at onwrite (_stream_writable.js:474:7) 
    at InflateRaw.afterTransform (_stream_transform.js:96:3) 
    at Zlib.processCallback (zlib.js:562:8) undefined 
```
Here is the code and packages installed:
```
({
  plugins: ['jsdom-quokka-plugin'],
  jsdom: {
    html: `
  <!DOCTYPE html>
  <html>
    <body>
      <canvas id="game-canvas" width="650" height="650"></canvas>
    </body>
  </html>
  `,
  },
});

function init(ctx: CanvasRenderingContext2D) {
    console.log(ctx.canvas.width)
}

const canvas = document.getElementById('game-canvas') as HTMLCanvasElement;
const ctx = canvas.getContext('2d') as CanvasRenderingContext2D;
init(ctx);
```
```
  "devDependencies": {
    "canvas": "^2.5.0",
  },
```
Your jdom version should be compatible with the canvas plugin:
https://github.com/jsdom/jsdom#canvas-support

> Since jsdom v13, version 2.x of canvas is required; version 1.x is no longer supported.

but is 6 months old, so is due to be updated :)

**Comment by David-Else** [comment]
I found another support ticket that told me to install `canvas` in `~/.quokka/`

Would be good if that was in the instructions.

**Comment by smcenlly** [comment]
Thanks for your feedback. We've updated our website docs on the `jsdom-quokka-plugin` docs to describe how to enable Web Canvas API.

**Comment by loganpowell** [comment]
I'm sorry for pinging on this old issue, but I can't seem to get this error/warning to go away. I've installed in the `.quokka` node_modules both `jsdom` and `canvas`... I've looked at the aforementioned quokka docs, but I'm not sure what I'm doing wrong... any pointers?

**Comment by smcenlly** [comment]
@loganpowell - we created a sample repo for you, which should help: https://github.com/wallabyjs/jsdom-quokka-canvas

**Comment by loganpowell** [comment]
Hmm... still struggling. I didn't have a `.quokka` file, but added one according to your spec. I also have a `config.json` that looks like this:

```json
{"pro":true,"node":"/Users/logan/AppData/Local/nvs/node/12.15.0/x64/node","plugins":["jsdom-quokka-plugin"],"jsdom":{},"stdEsm":true}
```

**Comment by smcenlly** [comment]
@loganpowell - could you please do the following:

1. Confirm that our sample is working for you?
2. Install canvas in your `~/.quokka/` directory: `npm install canvas` and see if that fixes your problem.
3. If (2) doesn't work, please deleting your global `.quokka` node_modules (`~/.quokka/node_modules` and `~/.quokka/package.json`) and then restart Quokka .
4. Confirm that the version of node used with `npm install` (e.g. `node --version`) is the same as the version specified in your `config.json` (if not, this may cause problems).

If you're still having problems, can you please [create a new issue in our Quokka support repository](https://github.com/wallabyjs/quokka/issues/new) and provide us with the exact code that you are attempting to run, as well as copy/paste or else a screenshot of the error you're receiving? If our sample is working for you and your project is not, it would also be a big help if you can provide us with a sample repo that's not working.
